/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(flow)'}/done` | `/done`; params?: Router.UnknownInputParams; } | { pathname: `${'/(flow)'}/quiz` | `/quiz`; params?: Router.UnknownInputParams; } | { pathname: `${'/(flow)'}/result` | `/result`; params?: Router.UnknownInputParams; } | { pathname: `${'/(flow)'}/scan` | `/scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(flow)'}/done` | `/done`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(flow)'}/quiz` | `/quiz`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(flow)'}/result` | `/result`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(flow)'}/scan` | `/scan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(flow)'}/done${`?${string}` | `#${string}` | ''}` | `/done${`?${string}` | `#${string}` | ''}` | `${'/(flow)'}/quiz${`?${string}` | `#${string}` | ''}` | `/quiz${`?${string}` | `#${string}` | ''}` | `${'/(flow)'}/result${`?${string}` | `#${string}` | ''}` | `/result${`?${string}` | `#${string}` | ''}` | `${'/(flow)'}/scan${`?${string}` | `#${string}` | ''}` | `/scan${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(flow)'}/done` | `/done`; params?: Router.UnknownInputParams; } | { pathname: `${'/(flow)'}/quiz` | `/quiz`; params?: Router.UnknownInputParams; } | { pathname: `${'/(flow)'}/result` | `/result`; params?: Router.UnknownInputParams; } | { pathname: `${'/(flow)'}/scan` | `/scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
